- id: Start
  pitch: 0.0
  yaw: 0.0
  roll: 0.0
  trans_z: 0.0
- id: Pos1
  pitch: -0.5
  yaw: 0.0
  roll: 0.0
  trans_z: 0.0
- id: Pos2
  pitch: -0.2
  yaw: 0.2
  roll: 0.0
  trans_z: 0.0
- id: Pos3
  pitch: -0.4
  yaw: 0.0
  roll: 0.0
  trans_z: 0.1